"""场景事件规格生成（agent 动态编排）的纯函数契约测试（行为冻结）。

覆盖 _normalize_event / _fallback_event 的输入输出契约。
所有用例不依赖 DeepSeek / RAG / 网络，与 test_fallback.py 风格一致。
"""
import pytest

import app as agent


def _good_spec():
    """一份结构完整的合法事件规格"""
    return {
        'event_id': 'agent_test_1',
        'title': '故人来访',
        'delivery': 'immediate',
        'fire_conditions': {},
        'reason': '突破后编排',
        'nodes': {
            'start': 'intro',
            'map': {
                'intro': {
                    'npc': '一位旧识找到了你。',
                    'choices': [
                        {'text': '寒暄', 'goto': 'talk'},
                        {'text': '离开', 'goto': 'leave'},
                    ],
                },
                'talk': {
                    'effects': [{'money': -500}, {'giveItem': {'name': '一阶回春丹', 'count': 5}}],
                    'npc': '旧识赠你丹药。',
                    'end': True,
                },
                'leave': {
                    'npc': '你转身离去。',
                    'end': True,
                },
            },
        },
    }


# ─────────────── _normalize_event ───────────────
class TestNormalizeEvent:
    def test_full_spec_keeps_structure(self):
        r = agent._normalize_event(_good_spec())
        assert r['event_id'] == 'agent_test_1'
        assert r['title'] == '故人来访'
        assert r['delivery'] == 'immediate'
        assert r['nodes']['start'] == 'intro'
        assert 'intro' in r['nodes']['map']
        assert r['nodes']['map']['talk']['effects'][0] == {'money': -500}

    def test_missing_title_raises(self):
        s = _good_spec()
        del s['title']
        with pytest.raises(ValueError):
            agent._normalize_event(s)

    def test_missing_nodes_raises(self):
        s = _good_spec()
        del s['nodes']
        with pytest.raises(ValueError):
            agent._normalize_event(s)

    def test_missing_map_raises(self):
        s = _good_spec()
        s['nodes'] = {'start': 'intro'}
        with pytest.raises(ValueError):
            agent._normalize_event(s)

    def test_start_not_in_map_raises(self):
        s = _good_spec()
        s['nodes']['start'] = 'nonexistent'
        with pytest.raises(ValueError):
            agent._normalize_event(s)

    def test_missing_event_id_autogenerated(self):
        s = _good_spec()
        del s['event_id']
        r = agent._normalize_event(s)
        assert r['event_id'].startswith('agent_')

    def test_invalid_delivery_falls_back_to_immediate(self):
        s = _good_spec()
        s['delivery'] = 'BOGUS'
        r = agent._normalize_event(s)
        assert r['delivery'] == 'immediate'

    def test_unknown_effect_key_dropped(self):
        """白名单外的 effect key 必须被剔除"""
        s = _good_spec()
        s['nodes']['map']['talk']['effects'] = [
            {'money': 100},
            {'giveSkill': {'id': 5}},  # 未注册，应被剔除
        ]
        r = agent._normalize_event(s)
        effs = r['nodes']['map']['talk']['effects']
        assert all('giveSkill' not in e for e in effs)
        assert {'money': 100} in effs

    def test_money_clamped(self):
        s = _good_spec()
        s['nodes']['map']['talk']['effects'] = [{'money': 99999999}]
        r = agent._normalize_event(s)
        assert r['nodes']['map']['talk']['effects'][0]['money'] <= 1000000

    def test_giveitem_count_clamped(self):
        s = _good_spec()
        s['nodes']['map']['talk']['effects'] = [{'giveItem': {'name': '丹', 'count': 9999}}]
        r = agent._normalize_event(s)
        assert r['nodes']['map']['talk']['effects'][0]['giveItem']['count'] <= 99

    def test_title_truncated(self):
        s = _good_spec()
        s['title'] = '甲' * 200
        r = agent._normalize_event(s)
        assert len(r['title']) <= 64

    def test_choice_goto_defaults_to_leave(self):
        s = _good_spec()
        s['nodes']['map']['intro']['choices'][0]['goto'] = ''
        r = agent._normalize_event(s)
        assert r['nodes']['map']['intro']['choices'][0]['goto'] == 'leave'

    def test_require_money_clamped(self):
        s = _good_spec()
        s['nodes']['map']['intro']['choices'][0]['require'] = {'money': 99999999}
        r = agent._normalize_event(s)
        assert r['nodes']['map']['intro']['choices'][0]['require']['money'] <= 1000000

    def test_non_object_input_raises(self):
        with pytest.raises(ValueError):
            agent._normalize_event([1, 2, 3])
        with pytest.raises(ValueError):
            agent._normalize_event('string')

    def test_roll_weights_positive(self):
        s = _good_spec()
        s['nodes']['map']['talk'] = {
            'roll': [{'weight': 0, 'goto': 'a'}, {'weight': -5, 'goto': 'b'}],
        }
        s['nodes']['map']['a'] = {'npc': 'a', 'end': True}
        s['nodes']['map']['b'] = {'npc': 'b', 'end': True}
        r = agent._normalize_event(s)
        roll = r['nodes']['map']['talk']['roll']
        assert all(x['weight'] >= 1 for x in roll)


# ─────────────── _fallback_event ───────────────
class TestFallbackEvent:
    def test_structure_complete(self):
        r = agent._fallback_event()
        assert r['event_id'].startswith('agent_fallback_')
        assert r['title']
        assert r['delivery'] == 'immediate'
        assert r['nodes']['start'] in r['nodes']['map']
        # 每个节点都有合法出口
        for nid, node in r['nodes']['map'].items():
            assert isinstance(node, dict)

    def test_fallback_effects_only_money(self):
        """降级事件只含安全的小额金钱，无危险 effect"""
        r = agent._fallback_event()
        for node in r['nodes']['map'].values():
            for eff in node.get('effects', []):
                assert 'money' in eff
                assert abs(eff['money']) <= 1000000


# ─────────────── effect 白名单常量 ───────────────
class TestEffectWhitelist:
    def test_keys_match_expected(self):
        expected = {
            'money', 'giveItem', 'forgeTask', 'createTask',
            'startBattle', 'grantCultivation', 'triggerEncounter', 'movePlayer',
        }
        assert set(agent.EVENT_EFFECT_KEYS) == expected
